# Generated by Django 5.1.2 on 2024-11-29 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0002_estabelecimento_descricao"),
    ]

    operations = [
        migrations.AddField(
            model_name="estabelecimento",
            name="imagem",
            field=models.ImageField(
                blank=True, null=True, upload_to="imgs/establishment/"
            ),
        ),
    ]
