# Generated by Django 5.1.2 on 2024-12-10 23:41

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0005_alter_cliente_user"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="cliente",
            name="dt_nasc",
        ),
        migrations.RemoveField(
            model_name="cliente",
            name="email",
        ),
        migrations.RemoveField(
            model_name="cliente",
            name="nome",
        ),
        migrations.AlterField(
            model_name="cliente",
            name="cpf",
            field=models.CharField(
                blank=True,
                max_length=14,
                validators=[django.core.validators.MinLengthValidator(14)],
            ),
        ),
    ]
