# Generated by Django 5.1.2 on 2024-12-13 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0009_pedido_itempedido"),
    ]

    operations = [
        migrations.AddField(
            model_name="pedido",
            name="concluido",
            field=models.BooleanField(default=False),
        ),
    ]
