# Generated by Django 5.1.2 on 2024-12-12 07:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0010_referencia"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Referencia",
        ),
    ]
